// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unixmerhujdxfsikiekp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuaXhtZXJodWpkeGZzaWtpZWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTA1MDcsImV4cCI6MjA1OTc2NjUwN30.hvraQkQ0fZv-hwhJ1_QB_xHY7zxpqPjo2bHCVeBH0IU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add custom types for working with auth users
export type AuthUser = {
  id: string;
  email?: string | null;
  user_metadata?: {
    full_name?: string;
    [key: string]: any;
  };
};

// Add custom type for user permissions
export type UserPermissions = {
  editSales: boolean;
  editSalesDetail: boolean;
  addSale: boolean;
  addSalesDetail: boolean;
  deleteSale: boolean;
  deleteSalesDetail: boolean;
  viewEmployees: boolean;
  editEmployees: boolean;
};

// Enhanced Profile type that includes permissions
export type EnhancedProfile = Database['public']['Tables']['profiles']['Row'] & {
  permissions?: UserPermissions;
  email?: string;
};

// Extend the Supabase client types to include admin functions
declare module '@supabase/supabase-js' {
  interface SupabaseAuthClient {
    admin: {
      listUsers(): Promise<{ 
        data: { 
          users: Array<{
            id: string;
            email?: string | null;
            user_metadata?: {
              full_name?: string;
              [key: string]: any;
            };
            [key: string]: any;
          }> 
        } | null;
        error: Error | null;
      }>;
    }
  }
}
