
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unixmerhujdxfsikiekp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuaXhtZXJodWpkeGZzaWtpZWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTA1MDcsImV4cCI6MjA1OTc2NjUwN30.hvraQkQ0fZv-hwhJ1_QB_xHY7zxpqPjo2bHCVeBH0IU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
